### ISSUE TITLE
Addition Param

### ISSUE THREAD

**Issue by Stan92** [showes/NgFlowSample#6] opened 2015-10-01 19:00 UTC
Hi,
It should be a stupid question but..
I would like to create a temporary folder from a data sent by the addtionalData

Currently from the controller, I have
var uploadProcessor = new FlowUploadProcessor("~/App_Data/Tmp/FileUploads");

How can I concatenate the extra param at this point?
Something like 
var uploadProcessor = new FlowUploadProcessor("~/App_Data/Tmp/FileUploads" + myParam );

Any help?

**Comment by samhowes** [comment] 2015-10-29 21:09
Duplicate of #4

**Closed as completed by samhowes** 2015-10-29 21:09 UTC
